name: Docker Image CI rpi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localhost:5000/boringtun-rpi:latest
    - name: Push the docker image
      run: docker push localhost:5000/boringtun-rpi:latest
